notifications: # set notification options
  email:
    recipients:
      - mgopez95@gmail.com
      - peter.kruczkiewicz@gmail.com

    # change is when the repo status goes from pass to fail or vice versa
    on_success: change
    on_failure: change

language: python
python:
  - '3.5'
  - '3.6'
os:
  - linux
#  - osx

# Whitelist of branches to run CI Testing on.
branches:
  only:
    - master

# Blacklist of branches to not run CI testing on.
# branches:
#  except:
#   - dontrunme 
#   - test 

before_install:
  - sudo apt-get -qq update;

install:
  - python setup.py install
  #Install pytest for testing.
  - pip install pytest

script:
  - pytest
