name: PyPI Deploy

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  pypi_deploy:
    name: PyPI Deploy
    runs-on: ubuntu-latest
    # Only run for the phac-nml/biohansel repo, for releases and pushes to master
    if: ${{ github.repository == 'phac-nml/biohansel' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: casperdcl/deploy-pypi@v2
        with:
          password: ${{ secrets.pypi_token }}
          build: true
          # only upload if a tag is pushed (otherwise just build & check)
          upload: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}